auctions/urls.py
from django.urls import path

from . import views


app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("listing/<str:id>", views.listing, name="listing"),
    path("listing/<str:id>/bid", views.bid, name="bid"),
    path("listing/<str:id>/addwatch", views.addwatch, name="addwatch"),
    path("listing/<str:id>/removewatch", views.removewatch, name="removewatch"),
    path("listing/<str:id>/close", views.close, name="close"),
    path("listing/<str:id>/comment", views.comment, name="comment"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("category/<str:id>", views.categoryListing, name="categoryListing"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    listingsWatched = models.ManyToManyField('Listing', blank=True, related_name="watchedBy")

class Category(models.Model):
    name = models.CharField(max_length = 64)

    def __str__(self):
        return f"{self.name}"

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usrBids")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    listing = models.ForeignKey('Listing', on_delete=models.CASCADE, related_name="listingBids")
    created_at = models.DateTimeField(auto_now_add=True)

class Listing(models.Model):
    title = models.CharField(max_length = 255)
    description = models.TextField()
    startingPrice = models.DecimalField(max_digits=10, decimal_places=2)
    imageLink = models.URLField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name="catListings", null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usrListings")
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    lastBid = models.ForeignKey(Bid, on_delete=models.SET_NULL, null=True, blank=True, related_name="bidListing")

    def bid(self, bid):
        if self.lastBid is None:
            if bid.price >= self.startingPrice:
                self.lastBid = Bid(bid)
            else:
                raise ValueError
        else:
            if bid.price > self.lastBid.price:
                self.lastBid = Bid(bid)
            else:
                raise ValueError

    def price(self):
        if self.lastBid is not None:
            return self.lastBid.price
        else:
            return self.startingPrice

class Comment(models.Model):
    comment = models.CharField(max_length=280)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usrComments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listingComments")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

auctions/forms.py
from django.forms import ModelForm, HiddenInput
from .models import Listing, Bid, Comment
from django.forms.widgets import TextInput, Textarea, NumberInput, URLInput

class ListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'description', 'imageLink', 'category', 'startingPrice']
        labels = {"title": "", "description": "", "imageLink": "", "startingPrice": ""}
        widgets = {
            'title': TextInput(attrs={  'placeholder': 'Title',
                                        'id': 'listingFormTitle'}),
            'description': Textarea(attrs={ 'placeholder': 'Type the auction description here',
                                            'id': 'listingFormDescription'}),
            'imageLink': URLInput(attrs={   'placeholder': 'Image URL Link',
                                            'id': 'listingFormImageLink'}),
            'startingPrice': NumberInput(attrs={'placeholder': 'Starting Price',
                                                'id': 'listingFormStartingPrice'}),
        }


class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['price']
        labels = {"price": "Bid"}

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from .models import User, Listing, Category
from .forms import ListingForm, BidForm, CommentForm

def index(request):
    listings = Listing.objects.filter(active=True)
    return renderListing(request, listings, "Active listings")

def categories(request):
    categories = Category.objects.all().order_by('name')
    return render(request, "auctions/categories.html", {
        "categories": categories
    })

def categoryListing(request, id):
    category = Category.objects.get(pk=id)
    listings = Listing.objects.filter(category=category, active=True)
    return renderListing(request, listings, f"{category.name} active listings")

@login_required(login_url="auctions:login")
def watchlist(request):
    listings = User.objects.get(username=request.user.username).listingsWatched.all()
    return renderListing(request, listings, "Watchlist")

def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url="auctions:login")
def create(request):
    if request.method == "POST":
        f = ListingForm(request.POST)
        if f.is_valid():
            new_listing = f.save(commit=False)
            new_listing.creator = request.user
            new_listing.save()
            f.save_m2m()
            # TODO: Go to listing page after creating
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return renderError(request, f.errors)
    else:
        return render(request, "auctions/create.html", {
            "createListingForm": ListingForm()
        })

def listing(request, id):
    l = getListing(id)
    return render(request, "auctions/listing.html", {
        "listing": l,
        "bidForm": BidForm(),
        "watchers": l.watchedBy.all(),
        "commentForm": CommentForm(),
        "comments": l.listingComments.all().order_by('-created_at'),
        "bidCount": getBidCount(id)
    })

@login_required(login_url="auctions:login")
def bid(request, id):
    l = getListing(id)
    f = BidForm(request.POST)
    if f.is_valid():
        # Get Bid object
        bid = f.save(commit=False)
        # Set bidder and relate to listing
        bid.bidder = request.user
        bid.listing = l
        try: # Try setting bid to listing
            l.bid(bid)
        except Exception as ex:
            return renderError(request, "Invalid Bid")
        else:
            # Save data
            bid.save()
            l.save()
            f.save_m2m()
            # Redirect to the listing page again
            return redirectToListing(id)
    else:
        return renderError(request, "Invalid Bid")

@login_required(login_url="auctions:login")
def addwatch(request, id):
    l = getListing(id)
    try:
        u = User.objects.get(username=request.user.username)
        u.listingsWatched.add(l)
        return redirectToListing(id)
    except Exception as e:
        return renderError(request, e)

@login_required(login_url="auctions:login")
def removewatch(request, id):
    l = getListing(id)
    try:
        u = User.objects.get(username=request.user.username)
        u.listingsWatched.remove(l)
        return redirectToListing(id)
    except Exception as e:
        return renderError(request, e)
    return redirectToListing(id)

@login_required(login_url="auctions:login")
def close(request, id):
    l = getListing(id)
    try:
        l.active = False
        l.save()
    except Exception as e:
        return renderError(request, e)
    else:
        return redirectToListing(id)

@login_required(login_url="auctions:login")
def comment(request, id):
    l = getListing(id)
    f = CommentForm(request.POST)
    if f.is_valid():
        # Get Comment object
        comm = f.save(commit=False)
        # Set commenter and relate to listing
        comm.commenter = request.user
        comm.listing = l
        # Save data
        comm.save()
        f.save_m2m()
        # Redirect to the listing page again
        return redirectToListing(id)
    else:
        return renderError(request, "Invalid comment")

# Auxiliary functions
def getListing(id):
    try:
        return Listing.objects.get(pk=id)
    except ObjectDoesNotExist:
        return renderError(request, "Listing not found.")
    except Exception as e:
        return renderError(request, e)

def getBidCount(id):
    try:
        return Listing.objects.get(pk=id).listingBids.count()
    except ObjectDoesNotExist:
        return renderError(request, "Listing not found.")
    except Exception as e:
        return renderError(request, e)

def renderError(request, message):
    return render(request, "auctions/error.html", {
        "message": message
    })

def redirectToListing(id):
    return HttpResponseRedirect(reverse("auctions:listing", kwargs={'id':id}))

def renderListing(request, listings, heading):
    return render(request, "auctions/index.html", {
        "listings": listings,
        "heading": heading
    })

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    <div class="categoriesContainer">
      {% for c in categories %}
      <div class="category">
        <a href="{% url 'auctions:categoryListing' c.id %}">{{ c }}</a>
      </div>
      {% empty %}
      No categories
      {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create New Listing</h2>

    {% if user.is_authenticated %}
      <div class="form_container">
        <form action="{% url 'auctions:create' %}" method="post" style="height:100%;width:100%">
          {% csrf_token %}
          {{ createListingForm.as_p }}
          <div class="button_container">
            <input class="submit_button" type="submit" value="Create">
          </div>
        </form>
      </div>
    {% else %}
    Not signed in.
    {% endif %}
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Error</h2>

    {{ message }}
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>{{ heading }}</h2>
    <div class="listingsContainer">
      {% for l in listings %}
      <a href="{% url 'auctions:listing' l.id %}">
        <div class="listingItem border">
          <div class="listingItemImage">
            {% if l.imageLink is not None %}
            <img class="itemImage" src="{{ l.imageLink }}">
            {% else %}
            <img class="itemImage" src="/static/image/no-image.png">
            {% endif %}
          </div>
          <div class="listingItemInfo">
            <div class="listingItemTitle">
              <span class="itemTitle">{{ l.title }}</span>
            </div>
            <div class="listingItemPrice">
              <span class="itemPrice">
                <strong>Price: </strong>$
                {% if l.lastBid is None %}
                  {{ l.startingPrice }}
                {% else %}
                  {{ l.lastBid.price }}
                {% endif %}
              </span>
            </div>
            <div class="listingItemDescription">
              <small class="itemDescription">{{ l.description }}</small>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'auctions:create' %}">Create New Listing</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
              </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
  <div class="listingHeaderContainer">
    <div class="listingTitleContainer">
      <h2>Listing: {{ listing.title }}</h2>
    </div>
    {% if user.is_authenticated %}
    <div class="listingWatchlistStarContainer">
      {% if user not in watchers %}
        <a href="{% url 'auctions:addwatch' listing.id %}">
          <img class="listingWatchlistStar" src="/static/image/icon/star.png" title="Add to Watchlist">
        </a>
      {% else %}
        <a href="{% url 'auctions:removewatch' listing.id %}">
          <img class="listingWatchlistStar" src="/static/image/icon/star-filled.png" title="Remove from Watchlist">
        </a>
      {% endif %}
    </div>
    {% endif %}
  </div>
  <div class="listingImageContainer">
    {% if listing.imageLink is not None %}
    <img class="listingImage" src="{{ listing.imageLink }}">
    {% else %}
    <img class="listingImage" src="/static/image/no-image.png">
    {% endif %}
  </div>
  <div class="listingDescriptionContainer">
    <small><span class="itemDescription">{{ listing.description }}</span></small>
  </div>
  <div class="listingPriceContainer">
    <span class="itemPrice">
      <strong>Price: </strong>$
      {% if listing.lastBid is None %}
        {{ listing.startingPrice }}<small><i>&nbsp;&nbsp;&nbsp;(No bids yet)</i></small>
      {% else %}
        {{ listing.lastBid.price }}
      {% endif %}
    </span>
  </div>
  {% if user.is_authenticated and listing.creator.username != user.username %}
  <div class="listingBidContainer">
    {% if listing.active %}
    <!-- Bid -->
    <form action="{% url 'auctions:bid' listing.id %}" method="post">
      {% csrf_token %}
      <div class="submitBidContainer">
        {{ bidForm }}
        <input class="submitBidButton btn btn-primary" type="submit" value="Place Bid">
      </div>
    </form>
    <!--  Comment -->
    <form action="{% url 'auctions:comment' listing.id %}" method="post">
      {% csrf_token %}
      <div class="submitCommentContainer">
        {{ commentForm }}
        <input class="submitCommentButton btn btn-secondary" type="submit" value="Publish">
      </div>
    </form>
    {% else %}
    <div class="submitBidContainer">
      <strong>Auction is closed.</strong>
      {% if listing.lastBid.bidder.username == user.username %}
      <strong>&nbsp;Congratulations! You won this auction.</strong>
      {% endif %}
    </div>
    {% endif %}
  </div>
  {% elif user.is_authenticated and listing.creator.username == user.username %}
  <div class="listingBidContainer">
    {% if listing.active %}
    <form action="{% url 'auctions:close' listing.id %}" method="post">
      {% csrf_token %}
      <div class="submitBidContainer">
        <input class="submitCloseButton btn btn-danger" type="submit" value="Close Auction">
      </div>
    </form>
    {% else %}
    <div class="submitBidContainer">
      <strong>Auction is closed. </strong>
      {% if listing.lastBid is not None %}
      <strong>&nbsp;{{ listing.lastBid.bidder.username }}&nbsp;has won this auction.</strong>
      {% endif %}
    </div>
    {% endif %}
  </div>
  {% endif %}
  <div class="detailsHeaderContainer">
    <h5>Details</h5>
  </div>
  <div class="detailsContainer">
    <p><small>{{ listing.creator.username }} started this auction on {{ listing.created_at }}</small></p>
    <p><small>{{ bidCount }} bids were made</p>
  </div>
  {% if user.is_authenticated %}
  <div class="latestCommentHeaderContainer">
    <h5>Latest comments</h5>
  </div>
  <div class="latestCommentContainer">
    {% for c in comments %}
    <div class="comment">
      <p><small><i>{{ c.commenter }} wrote on {{ c.created_at }}: "{{ c }}"</i></small></p>
    </div>
    {% empty %}
    <div class="comment">
      <p><small><i>No comments yet.</i></small></p>
    </div>
    {% endfor %}
  </div>
  {% endif %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}